/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input [15:0] io_dip,
    output reg [7:0] pina,
    output reg [7:0] pinb
  );
  
  
  
  
  always @* begin
    pina[0+7-:8] = io_dip[0+7-:8];
    pinb[0+7-:8] = io_dip[8+7-:8];
  end
endmodule
