/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     SIZE = 6
     DIV = 24
     TOP = 63
     UP = 1
*/
module counter_5 (
    input clk,
    input rst,
    output reg [5:0] value
  );
  
  localparam SIZE = 3'h6;
  localparam DIV = 5'h18;
  localparam TOP = 6'h3f;
  localparam UP = 1'h1;
  
  
  reg [29:0] M_ctr_d, M_ctr_q = 1'h0;
  
  localparam MAX_VALUE = 30'h3fffffff;
  
  always @* begin
    M_ctr_d = M_ctr_q;
    
    value = M_ctr_q[24+5-:6];
    if (1'h1) begin
      M_ctr_d = M_ctr_q + 1'h1;
      if (1'h1 && M_ctr_q == 30'h3fffffff) begin
        M_ctr_d = 1'h0;
      end
    end else begin
      M_ctr_d = M_ctr_q - 1'h1;
      if (1'h1 && M_ctr_q == 1'h0) begin
        M_ctr_d = 30'h3fffffff;
      end
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ctr_q <= 1'h0;
    end else begin
      M_ctr_q <= M_ctr_d;
    end
  end
  
endmodule
