/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module keypad_controller_3 (
    input [1:0] ind,
    input [3:0] pin,
    output reg [3:0] pinr,
    output reg move,
    output reg restart_game,
    output reg show_hint
  );
  
  
  
  wire [1-1:0] M_my_frame_x;
  wire [1-1:0] M_my_frame_y;
  wire [1-1:0] M_my_frame_keynum;
  reg [8-1:0] M_my_frame_pin;
  keypad_frame_8 my_frame (
    .pin(M_my_frame_pin),
    .x(M_my_frame_x),
    .y(M_my_frame_y),
    .keynum(M_my_frame_keynum)
  );
  
  reg [3:0] pinout;
  
  always @* begin
    move = 6'h2a;
    restart_game = 1'h0;
    show_hint = 1'h0;
    M_my_frame_pin[4+3-:4] = pin[0+3-:4];
    
    case (ind)
      1'h0: begin
        pinout = 10'h3e8;
      end
      1'h1: begin
        pinout = 7'h64;
      end
      2'h2: begin
        pinout = 4'ha;
      end
      2'h3: begin
        pinout = 1'h1;
      end
      default: begin
        pinout = 1'h0;
      end
    endcase
    pinr = pinout;
    M_my_frame_pin[0+3-:4] = pinout;
    if (M_my_frame_keynum <= 4'hb) begin
      move = M_my_frame_keynum;
    end else begin
      if (M_my_frame_keynum == 4'hc) begin
        restart_game = 1'h1;
      end else begin
        if (M_my_frame_keynum == 4'hf) begin
          show_hint = 1'h1;
        end
      end
    end
  end
endmodule
