/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module keypad_frame_8 (
    input [7:0] pin,
    output reg x,
    output reg y,
    output reg keynum
  );
  
  
  
  reg [3:0] col;
  
  reg [3:0] row;
  
  reg rownum;
  
  reg colnum;
  
  always @* begin
    col = pin[0+3-:4];
    row = pin[4+3-:4];
    
    case (row)
      10'h3e8: begin
        rownum = 1'h1;
      end
      7'h64: begin
        rownum = 2'h2;
      end
      4'ha: begin
        rownum = 2'h3;
      end
      1'h1: begin
        rownum = 3'h4;
      end
      default: begin
        rownum = 1'h0;
      end
    endcase
    
    case (col)
      10'h3e8: begin
        colnum = 1'h1;
      end
      7'h64: begin
        colnum = 2'h2;
      end
      4'ha: begin
        colnum = 2'h3;
      end
      1'h1: begin
        colnum = 3'h4;
      end
      default: begin
        colnum = 1'h0;
      end
    endcase
    x = rownum;
    y = colnum;
    if (rownum == 1'h0 || colnum == 1'h0) begin
      keynum = 1'h0;
    end else begin
      keynum = (rownum - 1'h1) * 3'h4 + (colnum - 1'h1);
    end
  end
endmodule
