/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module led_matrix_controller_2 (
    input [11:0] game,
    input [11:0] hint,
    input step,
    input [5:0] ind,
    input show_hint,
    output reg [11:0] pina,
    output reg [11:0] pinb
  );
  
  
  
  wire [12-1:0] M_my_frame_pina;
  wire [12-1:0] M_my_frame_pinb;
  reg [1-1:0] M_my_frame_x;
  reg [1-1:0] M_my_frame_y;
  reg [1-1:0] M_my_frame_yellow;
  led_matrix_frame_7 my_frame (
    .x(M_my_frame_x),
    .y(M_my_frame_y),
    .yellow(M_my_frame_yellow),
    .pina(M_my_frame_pina),
    .pinb(M_my_frame_pinb)
  );
  
  reg x;
  
  reg y;
  
  always @* begin
    x = ind / 4'h8 + 1'h1;
    y = ind - (ind / 4'h8) + 1'h1;
    M_my_frame_x = 1'h0;
    M_my_frame_y = 1'h0;
    M_my_frame_yellow = 1'h0;
    if (x <= 2'h3) begin
      if (y <= 3'h4) begin
        if (game[(x)*4+(y)*1+0-:1] == 1'h1) begin
          M_my_frame_x = x;
          M_my_frame_y = y;
        end
      end else begin
        if (show_hint == 1'h1) begin
          if (hint[(x)*4+(y - 3'h4)*1+0-:1] == 1'h1) begin
            M_my_frame_x = x;
            M_my_frame_y = y;
          end
        end
      end
    end else begin
      if (ind + step >= 7'h40) begin
        M_my_frame_x = x;
        M_my_frame_y = y;
      end
    end
    pina = M_my_frame_pina;
    pinb = M_my_frame_pinb;
  end
endmodule
