/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module op_adder_9 (
    input [5:0] alufn,
    input [11:0] a,
    input [11:0] b,
    output reg [11:0] ans,
    output reg z,
    output reg v,
    output reg n,
    output reg cmpz,
    output reg cmpv,
    output reg cmpn
  );
  
  
  
  reg [12:0] sum;
  
  reg [12:0] sub;
  
  always @* begin
    sub = a - b;
    
    case (alufn[0+1-:2])
      2'h0: begin
        sum = a + b;
      end
      2'h1: begin
        sum = a - b;
      end
      default: begin
        sum = a + b;
      end
    endcase
    ans = sum[0+11-:12];
    z = (~|sum);
    v = a[11+0-:1] & b[11+0-:1] & ~sum[11+0-:1] | ~a[11+0-:1] & ~b[11+0-:1] & sum[11+0-:1];
    n = sum[11+0-:1];
    cmpz = (~|sub);
    cmpv = a[11+0-:1] & ~b[11+0-:1] & ~sub[11+0-:1] | ~a[11+0-:1] & b[11+0-:1] & sub[11+0-:1];
    cmpn = sub[11+0-:1];
  end
endmodule
