/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module board_updater_1 (
    input [7:0] move,
    input [11:0] game,
    input [11:0] hint,
    input [143:0] mask,
    output reg [11:0] new_game,
    output reg [11:0] new_hint
  );
  
  
  
  reg [11:0] move_pos;
  
  always @* begin
    if (move != 6'h2a) begin
      new_game = game ^ mask[(move)*12+11-:12];
    end else begin
      new_game = game;
    end
    
    case (move)
      1'h0: begin
        move_pos = 12'h800;
      end
      1'h1: begin
        move_pos = 12'h400;
      end
      2'h2: begin
        move_pos = 12'h200;
      end
      2'h3: begin
        move_pos = 12'h100;
      end
      3'h4: begin
        move_pos = 12'h080;
      end
      3'h5: begin
        move_pos = 12'h040;
      end
      3'h6: begin
        move_pos = 12'h020;
      end
      3'h7: begin
        move_pos = 12'h010;
      end
      4'h8: begin
        move_pos = 12'h008;
      end
      4'h9: begin
        move_pos = 12'h004;
      end
      4'ha: begin
        move_pos = 12'h002;
      end
      4'hb: begin
        move_pos = 12'h001;
      end
      default: begin
        move_pos = 12'h000;
      end
    endcase
    new_hint = hint ^ move_pos;
  end
endmodule
