/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module keypad_frame_16 (
    input [7:0] pin,
    output reg [2:0] x,
    output reg [2:0] y,
    output reg [7:0] keynum
  );
  
  
  
  reg [3:0] col;
  
  reg [3:0] row;
  
  reg [2:0] rownum;
  
  reg [2:0] colnum;
  
  always @* begin
    col = pin[0+3-:4];
    row = pin[4+3-:4];
    
    case (row)
      4'h8: begin
        rownum = 3'h4;
      end
      4'h4: begin
        rownum = 2'h3;
      end
      4'h2: begin
        rownum = 2'h2;
      end
      4'h1: begin
        rownum = 1'h1;
      end
      default: begin
        rownum = 1'h0;
      end
    endcase
    
    case (col)
      4'h8: begin
        colnum = 3'h4;
      end
      4'h4: begin
        colnum = 2'h3;
      end
      4'h2: begin
        colnum = 2'h2;
      end
      4'h1: begin
        colnum = 1'h1;
      end
      default: begin
        colnum = 1'h0;
      end
    endcase
    x = rownum;
    y = colnum;
    if (rownum == 1'h0 || colnum == 1'h0) begin
      keynum = 6'h2a;
    end else begin
      keynum = (rownum - 1'h1) * 3'h4 + (colnum - 1'h1);
    end
  end
endmodule
